version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: qr_attendance_db
    environment:
      POSTGRES_DB: qr_attendance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qr_attendance_network

  app:
    build: .
    container_name: qr_attendance_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/qr_attendance_db
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
      - NODE_ENV=development
    depends_on:
      - postgres
    networks:
      - qr_attendance_network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  qr_attendance_network:
    driver: bridge
